spring:
  servlet:
    multipart:
      max-file-size: 10MB # File upload limit, default 1MB not enough.
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5433}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always

pms:
  jwt:
    secret-key: gPHjUuCb0wjGAFBrq6UF/eo5+t2bhY3KwY0WxIY+7i8=