services:

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - pms-pg-local:/var/lib/postgresql
    ports:
      - "5433:5432"

volumes:
  pms-pg-local:
